### PR TITLE
[Feature, 2058] Update validation rules

### PR DESCRIPTION
**Pull request by rimshakhalid**
**To reproduce error, follow these steps**

1. Create a new collection named 'Test BI 1'
2. Create an item named 'item 1 test' without any external source or Id
3. Create a csv file with above collection and item name but add external source and Id
4. Try to ingest csv and you will get unique name per collection constraint error

### _Fixes Applied_ (outdated)

- Created custom validation `UniqueItem` to validate item. Item is valid if
  - external id and source id is unique within collection
  - name is unique within collection
- Removed `UniqueItemNamePerCollection` constraint from Item model. 

    **Note:** I have to manually delete constraint from database table so we need to make sure to update staging/prod db is updated after deployment

### _To Discuss_ (see comments in jira ticket AMP-2058)
There is one thing that is remaining and I need some thoughts on it. 

1. Lets assume we have an item named 'rimsha 1' with an external source and id. And user try to ingest csv with same name 'rimsha 1' but without any external source and id. Currently implemented logic will update item already existed in database and it will ignore that ingest csv dont have external source and id. Is it ok or we need to handle it differently?

### _Updated Logic_
We are getting `transactional rollback exception` on failure which breaks whole process and send 500 error msg to user while batch ingest. To fix this, we need to check item with same name existed within collection before insert/update queries.

- When we have external source and id in ingest csv and found it in database we will
  - check whether item name matches the incoming itemName or not. 
    - If it matches we will return that item 
    - otherwise we will check incoming item name is unique within collection
      - if unique we will update current db item name
      - else we will check if incoming name with external src & id (incoming name + delimiter + external src + delimiter + external id) are unique within collection
        - if yes then we will update item name with this concatenated name
        - else return null item
- While creating new item when no matching item found, i checked whether item with same name(because name can be different from incoming name) existed if not create new otherwise return null
- If no new item created or we got from `getItem` throw exception

### CODE REVIEW

**Review by yingfeng-iu — CHANGES_REQUESTED** [review]
Hi Rimsha, I see you made some changes to validation annotation, which might have impacts on other part of the proj. Let's discuss the cause of the issue, and see if we have a less impacting fix.

**Review by yingfeng-iu — APPROVED** [review]
Looks great! thanks!

**Comment by rimshakhalid** [comment]
@yingfeng-iu I have disabled code for updating item information during batch ingest

**Comment by rimshakhalid** [comment]
Keeping current code to update name

**Pull request merged**
