### PR TITLE
Amp 651 user rejection

### PR DESCRIPTION
**Pull request by vinita84**

### CODE REVIEW

**Comment by mcwhitaker** [comment]
@yingfeng-iu @vinita84  - I think that we delete the row if rejected. Then we can still keep the boolean value. I know that Ying does not like to delete data, but I feel that for the pilot this is good enough. There won't be many rejected because there won't be many users.

**Comment by yingfeng-iu** [comment]
@mcwhitaker we already made the change. Also, i wanted to ask you about about account activation - when account is approved, user still need to click a link to activate the account. if we want to distinguish activated (confirmed) account vs not, we need a status to indicate the difference too, and some logic in login to check the account is activated before allowing login.

**Comment by mcwhitaker** [comment]
@yingfeng-iu I don't have a use case that requires us to know if the user has activated the account.

**Comment by yingfeng-iu** [comment]
@mcwhitaker what i meant is that, we did have story that impl the activation of account. and the purpose i remember is that we want to prevent Bot and such. if we don't do checking, then asking user to activate the account has no effect, right? am i missing something?

**Comment by vinita84** [comment]
@Maria when the user clicks on the account activation link, nothing happens
in the database. That part has not been implemented yet. I mentioned this
in the user account activation demo as well.

**Pull request merged**
